updated to find files in a directory and automatically determine them

diff --git a/bin/budget-buddy b/bin/budget-buddy
--- a/bin/budget-buddy
+++ b/bin/budget-buddy
@@ -7,13 +7,15 @@ DIR="$(cd "$(dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"
 # Verbose variable to set through command line
 VERBOSE=""
 
-# The financial source and file as provided by the user
+# Setting that can be set through the command line
 FIN_SRC_PROVIDED=""
 FILE_PROVIDED=""
+SEARCH_DIR=""
 
-# Staging (temporary) and output directories
+# Staging (temporary), output, and ruleset directories
 TMP_DIR="${DIR}/../tmp"
 OUTPUT_DIR="${DIR}/../output"
+RULESETS_DIR="${DIR}/../rulesets"
 
 # Source in the core functions from the lib/ directory
 source "${DIR}/../lib/transform.sh"
@@ -43,6 +45,10 @@ while (( "$#" )); do
 	    FIN_SRC_PROVIDED="${2}"
 	    shift 2
 	    ;;
+	"-d" | "--directory")
+	    SEARCH_DIR="${2}"
+	    shift 2
+	    ;;
 	*)
 	    printf "WARN: Unrecognized option ${1}\n"
 	    shift
@@ -59,7 +65,7 @@ if [ "${FIN_SRC_PROVIDED}" = "" ] ||
        [ "${FILE_PROVIDED}" = "" ]; then
     printf "ERROR: no financial source or file provided\n"
     printf "  $ budget-buddy --help\n"
-    exit 1
+#    exit 1
 fi
 
 # Boolean to determine if the financial source provided by the user
@@ -76,17 +82,57 @@ done
 if [ "${FIN_SRC_PRESENT}" = 0 ]; then
     printf "ERROR: The script currently doesn't support financial "
     printf "source ${FIN_SRC_PROVIDED}\n"
-    exit 2
+#    exit 2
 fi
 
 mkdir -p "${TMP_DIR}"
 mkdir -p "${OUTPUT_DIR}"
 
-TMP_FILE="${TMP_DIR}/${FIN_SRC_PROVIDED}-tmp.txt"
-OUT_FILE="${OUTPUT_DIR}/${FIN_SRC_PROVIDED}.txt"
-
 #check_for_ruleset_file $src
-column_transform "${FIN_SRC_PROVIDED}" "${FILE_PROVIDED}" "${TMP_FILE}"
-#ruleset_transform "${FIN_SRC_PROVIDED}" "${TMP_FILE}" "${OUT_FILE}"
+#if [ ! "${SEARCH_DIR}" = "" ]; then
+#    detect_source_files "${TMP_DIR}" "${SEARCH_DIR}"
+#fi
 
+for fin_src in "${FINANCE_SOURCES[@]}"; do
+    mkdir -p "${TMP_DIR}/${fin_src}"
+done
+
+for line in $(find "${SEARCH_DIR}" -type f); do
+    # grab the filename from the absolute path
+    filename="$(basename ${line})"
+    # grab the first line from the file and trim non-ascii chars
+    title="$(head -1 $line | tr -d '[:cntrl:]')"
+    
+    # we can't use case statements w/regex so we run multi-line
+    # if statements :grimace:
+
+    # lets start w chase
+    if [[ "${filename}" =~ \
+			^Chase[0-9]{4}_Activity.*\.CSV$ ]] &&
+	   [ "${title}" = \
+			"Transaction Date,Post Date,Description,Category,Type,Amount" ]; then
+	echo "chase"
+	handle_single_file "${TMP_DIR}/chase" \
+			   "${OUTPUT_DIR}/chase" \
+			   "${RULESETS_DIR}" \
+			   "${line}" \
+			   "chase"
+	# capital one
+    elif [[ "${filename}" =~ \
+			  ^[0-9]{4}-[0-9]{2}-[0-9]{2}_transaction_download.* ]] &&
+	     [ "${title}" = \
+			  "Transaction Date,Posted Date,Card No.,Description,Category,Debit,Credit" ]; then
+	echo "capital one"
+	# usaa
+    elif [[ "${filename}" =~ ^bk_download.*\.csv$ ]]; then
+	echo "usaa"
+	# bank of america
+    elif [[ "${filename}" =~ ^.*[0-9]{4}_[0-9]{4}\.csv$ ]] &&
+	     [ "${title}" = \
+			  "Posted Date,Reference Number,Payee,Address,Amount" ]; then
+	echo "boa"
+    fi    
+done
+
+# Clean up!
 # rm -rf "${TMP_DIR}"
